### ISSUE TITLE
[FEATURE] Add support for some textures & items

### ISSUE THREAD

**Issue by GentlemanMC** [ViaVersion/ViaForge#31]
for example :
respawn anchors dont show up
crying obsidian doesnt show up
netherite stuff show as diamond stuff

what to do:
add the textures to the assets folder and make the game renders them somehow

**Comment by GentlemanMC** [comment]
this is important for pvp

**Comment by FlorianMichael** [comment]
added on TODO

**Comment by GentlemanMC** [comment]
nice

**Comment by HowardZHY** [comment]
I remember there was a texture pack for 1.14? to show 1.16 blocks and items?

**Comment by GentlemanMC** [comment]
> I remember there was a texture pack for 1.14? to show 1.16 blocks and items?

this mod is for 1.12.2

**Comment by HowardZHY** [comment]
not the mod, i mean a texture pack that can show some new item and block's textures base on NBT (such as copper translated as an iron block with an (name:1.xx Copper) NBT tag, the texture pack will show this translated *iron* (copper) block with copper texture.



在 2022-06-10 19:29:44，"Gentleman" ***@***.***> 写道：

I remember there was a texture pack for 1.14? to show 1.16 blocks and items?

this mod is for 1.12.2

**Comment by GentlemanMC** [comment]
> not the mod, i mean a texture pack that can show some new item and block's textures base on NBT (such as copper translated as an iron block with an (name:1.xx Copper) NBT tag, the texture pack will show this translated *iron* (copper) block with copper texture. 在 2022-06-10 19:29:44，"Gentleman" ***@***.***> 写道： I remember there was a texture pack for 1.14? to show 1.16 blocks and items? this mod is for 1.12.2 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

could you provide a link please?

**Comment by HowardZHY** [comment]
I remember there was one on vv's discord, but I don't have it.



在 2022-06-11 20:13:33，"Gentleman" ***@***.***> 写道：

not the mod, i mean a texture pack that can show some new item and block's textures base on NBT (such as copper translated as an iron block with an (name:1.xx Copper) NBT tag, the texture pack will show this translated iron (copper) block with copper texture. 在 2022-06-10 19:29:44，"Gentleman" @.> 写道： I remember there was a texture pack for 1.14? to show 1.16 blocks and items? this mod is for 1.12.2 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

could you provide a link please?

**Comment by HowardZHY** [comment]
https://www.planetminecraft.com/texture-pack/1-7-2-1-12-2-optifine-netherite-items-and-armor-on-viaversion-server/

**Comment by blue-dragon-cairo** [comment]
will it be also possible to add waterlogged block support, or will it be too time consuming like in readme?

**Comment by FlorianMichael** [comment]
Support for new blocks/items/features in older versions will never be added to ViaForge, if you want newer features, use newer versions, checkout https://github.com/ViaVersionAddons/ViaBackwards-Plus for some backporting.
